version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=canaan_db
      - MYSQL_USER=canaan_user
      - MYSQL_PASSWORD=canaan_password

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=canaan_db
      - MYSQL_USER=canaan_user
      - MYSQL_PASSWORD=canaan_password
      - MYSQL_ROOT_PASSWORD=root_password

volumes:
  mysql_data:
